# Created using wingetcreate 1.9.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Microsoft.VisualStudio.Enterprise
PackageVersion: 18.0.0
InstallerSwitches:
  Silent: --quiet
  SilentWithProgress: --passive
  Upgrade: update
  Custom: --wait
ExpectedReturnCodes:
- InstallerReturnCode: 1001
  ReturnResponse: installInProgress
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 1618
  ReturnResponse: installInProgress
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 1003
  ReturnResponse: fileInUse
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 1641
  ReturnResponse: rebootInitiated
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 3010
  ReturnResponse: rebootRequiredToFinish
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5004
  ReturnResponse: cancelledByUser
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8001
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8002
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8003
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8004
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8005
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8007
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8008
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8009
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: -1073720687
  ReturnResponse: noNetwork
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: -2146233083
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 740
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5001
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5002
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5003
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5005
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5007
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5008
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8006
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
Commands:
- devenv
Installers:
- Architecture: x64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://download.visualstudio.microsoft.com/download/pr/c542a5db-b2a4-49ec-840e-a6336f32e619/452b49e73316f43d962aed860f9f3b6cdf7e7b151696b8f28008bfba31c945d5/vs_Enterprise.exe
  InstallerSha256: 452b49e73316f43d962aed860f9f3b6cdf7e7b151696b8f28008bfba31c945d5
ManifestType: installer
ManifestVersion: 1.9.0
