# Created using wingetcreate 1.9.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Microsoft.VisualStudio.Enterprise.Insiders
PackageVersion: 18.0.11012.119
InstallerSwitches:
  Silent: --quiet
  SilentWithProgress: --passive
  Upgrade: update
  Custom: --wait
ExpectedReturnCodes:
- InstallerReturnCode: 1001
  ReturnResponse: installInProgress
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 1618
  ReturnResponse: installInProgress
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 1003
  ReturnResponse: fileInUse
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 1641
  ReturnResponse: rebootInitiated
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 3010
  ReturnResponse: rebootRequiredToFinish
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5004
  ReturnResponse: cancelledByUser
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8001
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8002
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8003
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8004
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8005
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8007
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8008
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8009
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: -1073720687
  ReturnResponse: noNetwork
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: -2146233083
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 740
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5001
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5002
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5003
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5005
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5007
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5008
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8006
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
Commands:
- devenv
AppsAndFeaturesEntries:
- DisplayVersion: 18.0.0 Insiders [11012.119]
Installers:
- Architecture: x64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://download.visualstudio.microsoft.com/download/pr/2f6c7854-9f0b-43d4-9977-e8ad6fe3b74e/fd0c66679f149616a7c5dff7817abd24d0ce2a221b483697c00b325faaba57f2/vs_Enterprise.exe
  InstallerSha256: fd0c66679f149616a7c5dff7817abd24d0ce2a221b483697c00b325faaba57f2
ManifestType: installer
ManifestVersion: 1.9.0
